---
pageInfo:
  title: HAL9000
  description: Welcome to the Gray Family Homelab!
  navLinks:
  - title: GitHub
    path: https://github.com/james-gray/nix-config
  - title: Blog
    path: https://jgray.me

# Optional app settings and configuration
appConfig:
  theme: default
  statusCheck: true

# Main content - An array of sections, each containing an array of items
sections:
- name: Apps
  icon: fas grid-horizontal
  items:
  - title: Nextcloud
    description: Our own personal Google Drive.
    icon: si-nextcloud
    url: https://nextcloud.jgray.me/
    target: newtab
  - title: Home Assistant
    description: Control panel for the Gray Family home.
    url: https://hass.jgray.me/
    icon: si-homeassistant
- name: Monitoring
  icon: fas fa-chart-line
  items:
    - title: Netdata
      description: System monitoring and information. Must be on Tailnet to access.
      icon: si-netdata
      url: http://hal9000:19999
