---
version: "3"
services:
  dashy:
    ports:
      - 28080:8080
    volumes:
      - /home/jamesgray/code/nix-config/dashy-config.yml:/app/user-data/conf.yml
    container_name: dashy
    tty: true
    stdin_open: true
    restart: always
    image: lissy93/dashy:latest
