version: '3'

services:
  vaultwarden:
    container_name: vaultwarden
    user: 1000:100
    image: vaultwarden/server:1.32.0
    restart: unless-stopped
    volumes:
      - /tank9000/ds1/vaultwarden/data/:/data/
    ports:
      - 180:80
    env_file:
      - /run/agenix/vw-env
