version: '3'
services:
  actual_server:
    image: docker.io/actualbudget/actual-server:latest
    user: 1000:100
    ports:
      # This line makes Actual available at port 5006 of the device you run the server on,
      # i.e. http://localhost:5006. You can change the first number to change the port, if you want.
      - '5006:5006'
    environment:
      - ACTUAL_PORT=5006
    volumes:
      - /tank9000/ds1/actual/actual-data:/data
    restart: unless-stopped
