version: "3"
services:
  navidrome:
    container_name: navidrome
    image: deluan/navidrome:latest
    user: 1000:100 # should be owner of volumes
    ports:
      - "24533:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
    volumes:
      - "/tank9000/ds1/navidrome/data/Music:/data"
      - "/tank9000/ds1/navidrome/music/Music:/music:ro"
