version: "3"
services:
  bandcamp:
    container_name: bandcamp
    image: deluan/navidrome:latest
    user: 1000:100 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
    env_file:
      - /run/agenix/bandcamp-env
    volumes:
      - "/tank9000/ds1/navidrome/data/Bandcamp:/data"
      - "/tank9000/ds1/navidrome/music/Bandcamp:/music:ro"
