---
version: "3"
services:
  all-in-one:
    container_name: nextcloud-aio-mastercontainer
    restart: always
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 18080:8080
    environment:
      - APACHE_PORT=11000
      - NEXTCLOUD_DATADIR=/tank9000/ds1/nextcloud
      - PHP_MEMORY_LIMIT=1024M
      - PHP_UPLOAD_LIMIT=1024M
      - NEXTCLOUD_ADDITIONAL_PHP_EXTENSIONS=imagick libva-utils libva-vdpau-driver libva-intel-driver intel-media-driver mesa-va-gallium
    image: nextcloud/all-in-one:latest
volumes:
  # NOTE: Need to create the docker volume first: $ docker volume create nextcloud_aio_mastercontainer
  # TODO: See about making this more elegant
  nextcloud_aio_mastercontainer:
    external: true
