version: "3"
services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 680:8080
    environment:
      TZ: "America/Vancouver"
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_DEBUG: true
      WATCHTOWER_SCHEDULE: "0 0 3 * * *"
