version: "3"
services:
  ipod:
    container_name: ipod
    image: deluan/navidrome:latest
    user: 1003:986 # should be owner of volumes
    ports:
      - "14533:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
    env_file:
      - /run/agenix/ipod-env
    volumes:
      - "/tank9000/ds1/navidrome/data/iPod:/data"
      - "/tank9000/ds1/navidrome/music/iPod:/music:ro"
