version: '3.5'

services:
  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    cap_add:
      - SYS_RAWIO
    ports:
      - "38080:8080" # webapp
      - "38086:8086" # influxDB admin
    volumes:
      - /run/udev:/run/udev:ro
      - /home/jamesgray/code/nix-config/scrutiny/config:/opt/scrutiny/config
      - /home/jamesgray/code/nix-config/scrutiny/influxdb:/opt/scrutiny/influxdb
    devices:
      - "/dev/sda"
      - "/dev/sdb"
      - "/dev/sdc"
      - "/dev/sdd"
      - "/dev/sde"
