services:
  wordpress-db:
    image: mysql:8.0
    container_name: wordpress-db
    volumes:
      - /tank9000/ds1/wordpress/dbdata:/var/lib/mysql
    restart: unless-stopped
    env_file:
      - /run/agenix/wordpress-env
    networks:
      - wordpress-network

  wordpress:
    depends_on:
      - wordpress-db
    image: wordpress:6.6.1-php8.1-fpm
    container_name: wordpress
    restart: unless-stopped
    volumes:
      - /tank9000/ds1/wordpress/wordpress:/var/www/html
    env_file:
      - /run/agenix/wordpress-env
    networks:
      - wordpress-network

  wordpress-webserver:
    depends_on:
      - wordpress
    image: nginx:1.15.12-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "380:80"
    volumes:
      - /tank9000/ds1/wordpress/wordpress:/var/www/html
      - /tank9000/ds1/wordpress/nginx-conf:/etc/nginx/conf.d
    networks:
      - wordpress-network

networks:
  wordpress-network:
    driver: bridge
