mqtt:
  enabled: true
  host: 192.168.1.65
  port: 1883
  topic_prefix: zigbee2mqtt/frigate
  client_id: frigate

birdseye:
  enabled: true
  mode: continuous

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-copy

go2rtc:
  streams:
    doorbell:
    - ffmpeg:http://192.168.1.73/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password={FRIGATE_RTSP_PASSWORD}#video=copy#audio=copy#audio=opus
    doorbell_sub:
    - ffmpeg:http://192.168.1.73/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password={FRIGATE_RTSP_PASSWORD}
    - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.73:544/h264Preview_01_sub

cameras:
  doorbell:
    enabled: true
    ffmpeg:
      inputs:
        # High Res stream
      - path: rtsp://127.0.0.1:8554/doorbell
        input_args: preset-rtsp-restream
        roles:
        - record
        # Low Res stream
      - path: rtsp://127.0.0.1:8554/doorbell_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
        - audio
    detect:
      width: 640
      height: 480
      fps: 10
    objects:
      filters:
        person:
          mask:
          - 0,480,246,480,234,0,0,0
        car:
          mask:
          - 640,266,532,263,525,317,640,334
      track:
      - person
      - cat
      - bird
    rtmp:
      enabled: false
    snapshots:
      enabled: true
    record:
      enabled: true
      retain:
        days: 5
      events:
        retain:
          default: 10
    motion:
      mask:
      - 0,480,246,480,234,0,0,0
