services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    volumes:
      - /tank9000/ds1/uptimekuma/data:/app/data
    ports:
      # <Host Port>:<Container Port>
      - 3001:3001
    restart: unless-stopped
