---
services:
  unifi-db:
    image: docker.io/mongo:7.0
    container_name: unifi-db
    user: 1000:100
    volumes:
      - /tank9000/ds1/unifi/db:/data/db
      - /run/agenix/unifi-init-mongo:/docker-entrypoint-initdb.d/init-mongo.js:ro
    restart: unless-stopped
  unifi-network-application:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: unifi-network-application
    env_file:
      - /run/agenix/unifi-network-application-env
    volumes:
      - /tank9000/ds1/unifi/config:/config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp
      - 8843:8843
      - 8880:8880
      - 6789:6789
      - 5514:5514/udp
    restart: unless-stopped
