---
pageInfo:
  title: HAL9000
  description: Welcome to the Gray Family Homelab!
  navLinks:
  - title: GitHub
    path: https://github.com/james-gray/nix-config
  - title: Blog
    path: https://jgray.me

# Optional app settings and configuration
appConfig:
  theme: default

# Main content - An array of sections, each containing an array of items
sections:
- name: Apps
  icon: fab fa-app-store
  items:
  - title: Nextcloud
    description: Our own personal Google Drive.
    icon: hl-nextcloud
    url: https://nextcloud.jgray.me/
    target: newtab
    statusCheck: true
  - title: Home Assistant
    description: Control panel for the Gray Family home.
    url: https://hass.jgray.me/
    icon: hl-home-assistant
    statusCheck: true
  - title: Jellyfin
    description: Home media server.
    url: https://jellyfin.jgray.me/
    icon: hl-jellyfin
    statusCheck: true
  - title: Vaultwarden
    description: Password manager.
    url: https://vw.jgray.me/
    icon: hl-vaultwarden
    statusCheck: true
  - title: Mealie
    description: Recipe management app.
    url: https://mealie.jgray.me/
    icon: hl-mealie
    statusCheck: true
  - title: Actual
    description: Budgeting software / YNAB clone.
    url: https://actual.jgray.me/
    icon: hl-actual
    statusCheck: true
  - title: LubeLogger
    description: Car maintenance tracker.
    url: https://lubelogger.jgray.me/
    icon: hl-lubelogger
    statusCheck: true
  - title: Frigate
    description: NVR/CCTV application. Must be on Tailnet to access.
    url: http://hal9000:5000/
    icon: hl-frigate
    statusCheck: false
- name: Monitoring
  icon: fas fa-chart-line
  items:
    - title: Netdata
      description: System monitoring and information. Must be on Tailnet to access.
      icon: hl-netdata
      url: http://hal9000:19999
      target: newtab
      statusCheck: false
    - title: Scrutiny
      description: Smart monitoring of system drives. Must be on Tailnet to access.
      icon: hl-scrutiny
      url: http://hal9000:38080
      target: newtab
      statusCheck: false
    - title: Cockpit
      description: Server administration tool. Must be on Tailnet to access.
      icon: hl-cockpit
      url: http://hal9000:9090
      target: newtab
      statusCheck: false
    - title: Uptime Kuma
      description: Uptime monitoring. Must be on Tailnet to access.
      icon: hl-uptime-kuma
      url: http://hal9000:3001
      target: newtab
      statusCheck: false
- name: Network
  icon: fas fa-globe
  items:
    - title: AdGuard Home
      description: DNS-based adblock. Must be on home network to access.
      icon: hl-adguardhome
      url: http://192.168.1.88:8083
      target: newtab
      statusCheck: false
    - title: UniFi Network Application
      description: UniFi Wi-Fi access point configurator. James' MacBook Pro must be on and connected to Tailnet to access.
      icon: hl-unifi
      url: https://100.111.96.38:8443
      target: newtab
      statusCheck: false
    - title: EdgeMax EdgeRouter-X SRP Interface
      description: Router configuration admin interface. Must be on home network to access.
      icon: fas fa-network-wired
      url: https://192.168.1.1
      target: newtab
      statusCheck: false
    - title: Shaw Gateway Interface
      description: Modem configuration admin interface. Must be on home network to access.
      icon: fas fa-network-wired
      url: https://10.0.0.1
      target: newtab
      statusCheck: false
