---
pageInfo:
  title: HAL9000
  description: Welcome to the Gray Family Homelab!
  navLinks:
  - title: GitHub
    path: https://github.com/james-gray/nix-config
  - title: Blog
    path: https://jgray.me

# Optional app settings and configuration
appConfig:
  theme: default
  auth:
    users:
    - user: jamesgray
      hash: 6DF68A88E769A29B0B69654B1B52A4765B510B7705FF555A63BDFC48E9F67547
      type: admin

# Main content - An array of sections, each containing an array of items
sections:
- name: Apps
  icon: fab fa-app-store
  items:
  - title: Open WebUI
    description: Frontend for various local LLMs running in Ollama.
    icon: hl-open-webui
    url: https://oi.jgray.me/
    statusCheck: true
  - title: Nextcloud
    description: Our own personal Google Drive.
    icon: hl-nextcloud
    url: https://nextcloud.jgray.me/
    target: newtab
    statusCheck: true
  - title: Home Assistant
    description: Control panel for the Gray Family home.
    url: https://hass.jgray.me/
    icon: hl-home-assistant
    statusCheck: true
  - title: Vaultwarden
    description: Password manager.
    url: https://vw.jgray.me/
    icon: hl-vaultwarden
    statusCheck: true
  - title: Mealie
    description: Recipe management app.
    url: https://mealie.jgray.me/
    icon: hl-mealie
    statusCheck: true
  - title: Miniflux
    description: RSS reader.
    url: https://miniflux.jgray.me/
    icon: hl-miniflux
    statusCheck: true
  - title: Actual
    description: Budgeting software / YNAB clone.
    url: https://actual.jgray.me/
    icon: hl-actual
    statusCheck: true
  - title: LubeLogger
    description: Car maintenance tracker.
    url: https://lubelogger.jgray.me/
    icon: hl-lubelogger
    statusCheck: true
  - title: Christmas Community
    description: Christmas wishlist app.
    icon: favicon
    url: https://christmas.jgray.me/
    target: newtab
    statusCheck: true
  - title: Frigate
    description: NVR/CCTV application.
    url: https://frigate.jgray.me
    icon: hl-frigate
    statusCheck: true
- name: Media
  icon: fas fa-compact-disc
  items:
  - title: Jellyfin
    description: Home media server.
    url: https://jellyfin.jgray.me/
    icon: hl-jellyfin
    statusCheck: true
  - title: Bandcamp (Navidrome)
    description: Bandcamp music collection Navidrome server.
    url: https://bandcamp.jgray.me/
    icon: hl-navidrome
    statusCheck: true
  - title: iPod (Navidrome)
    description: iPod music collection Navidrome server.
    url: https://ipod.jgray.me/
    icon: hl-navidrome
    statusCheck: true
  - title: Music (Navidrome)
    description: Music collection (CDs and records) Navidrome server.
    url: https://music.jgray.me/
    icon: hl-navidrome
    statusCheck: true
  - title: Sonarr
    description: TV Series Media Manager. Must be on Tailnet to access.
    url: http://hal9000:8989
    icon: hl-sonarr
    statusCheck: false
  - title: Radarr
    description: Movie Media Manager. Must be on Tailnet to access.
    url: http://hal9000:7878
    icon: hl-radarr
    statusCheck: false
  - title: Lidarr
    description: Music Media Manager. Must be on Tailnet to access.
    url: http://hal9000:8686
    icon: hl-lidarr
    statusCheck: false
  - title: Music Assistant
    description: Music Assistant media player manager. Must be on Tailnet to access.
    url: http://hal9000:8095
    icon: hl-music-assistant
    statusCheck: false
- name: Monitoring
  icon: fas fa-chart-line
  items:
    - title: Netdata
      description: System monitoring and information. Must be on Tailnet to access.
      icon: hl-netdata
      url: http://hal9000:19999
      target: newtab
      statusCheck: false
    - title: Scrutiny
      description: Smart monitoring of system drives. Must be on Tailnet to access.
      icon: hl-scrutiny
      url: http://hal9000:38080
      target: newtab
      statusCheck: false
    - title: Cockpit
      description: Server administration tool.
      icon: hl-cockpit
      url: https://cockpit.jgray.me
      target: newtab
      statusCheck: true
    - title: Uptime Kuma
      description: Uptime monitoring. Must be on Tailnet to access.
      icon: hl-uptime-kuma
      url: http://hal9000:3001
      target: newtab
      statusCheck: false
    - title: Portainer
      description: Docker container manager. Must be on Tailnet to access.
      icon: hl-portainer
      url: http://hal9000:9000
      statusCheck: false
- name: Network
  icon: fas fa-globe
  items:
    - title: AdGuard Home
      description: DNS-based adblock.
      icon: hl-adguardhome
      url: https://adguard.jgray.me
      target: newtab
      statusCheck: true
    - title: UDM Network Application
      description: UniFi Wi-Fi admin panel.
      icon: hl-unifi
      url: https://unifi.jgray.me
      target: newtab
      statusCheck: true
    - title: Mikrotik SwOS
      desription: Microtik admin panel. Must be on home network to access.
      icon: si-mikrotik
      url: http://192.168.1.2
      target: newtab
      statusCheck: false
    - title: Zigbee2MQTT
      description: MQTT management web interface.
      icon: hl-mqtt
      url: https://mqtt.jgray.me
      target: newtab
      statusCheck: true
    - title: CUPS
      description: Print server.
      icon: hl-cups
      url: https://cups.jgray.me
      target: newtab
      statusCheck: true
