---
pageInfo:
  title: HAL9000
  description: Welcome to the Gray Family Homelab!
  navLinks:
  - title: GitHub
    path: https://github.com/james-gray/nix-config
  - title: Blog
    path: https://jgray.me

# Optional app settings and configuration
appConfig:
  theme: default

# Main content - An array of sections, each containing an array of items
sections:
- name: Apps
  icon: fab fa-app-store
  items:
  - title: Nextcloud
    description: Our own personal Google Drive.
    icon: hl-nextcloud
    url: https://nextcloud.jgray.me/
    target: newtab
    statusCheck: true
  - title: Home Assistant
    description: Control panel for the Gray Family home.
    url: https://hass.jgray.me/
    icon: hl-home-assistant
    statusCheck: true
  - title: Jellyfin
    description: Home media server.
    url: https://jellyfin.jgray.me/
    icon: hl-jellyfin
    statusCheck: true
  - title: Vaultwarden
    description: Password manager.
    url: https://vw.jgray.me/
    icon: hl-vaultwarden
    statusCheck: true
- name: Monitoring
  icon: fas fa-chart-line
  items:
    - title: Netdata
      description: System monitoring and information. Must be on Tailnet to access.
      icon: hl-netdata
      url: http://hal9000:19999
      target: newtab
      statusCheck: false
    - title: Scrutiny
      description: Smart monitoring of system drives. Must be on Tailnet to access.
      icon: hl-scrutiny
      url: http://hal9000:38080
      target: newtab
      statusCheck: false
    - title: Cockpit
      description: Server administration tool. Must be on Tailnet to access.
      icon: hl-cockpit
      url: http://hal9000:9090
      target: newtab
      statusCheck: false
